#ifndef _H_KEYSTORE_DEFS_H_
#define _H_KEYSTORE_DEFS_H_

#define USERNAME_SIZE 21
#define PASSWORD_SIZE 21

#define MAX_TRIGGERS 20
#define MAX_ACTIONS 20
#define TRIGGER_KEY_SIZE 32
#define ACTION_KEY_SIZE 32
#define RULE_KEY_SIZE 32

#define RUNTIME_BIN_HASH_SIZE 64
#define EAPP_BIN_HASH_SIZE 64
#define SM_BIN_HASH_SIZE 64

#endif