add_wolfssl(${bin_name}-wolfssl
   "48cb185ce9a5e6e9d3857eede39591475c2d5fdd" #Last mainline commit
   "musl"
   "-DWOLFSSL_SMALL_STACK -DWOLFSSL_CUSTOM_OID -DHAVE_OID_ENCODING -DHAVE_OID_DECODING -DOPENSSL_EXTRA -DWOLFSSL_VERIFY_CB_ALL_CERTS -DWOLFSSL_ALWAYS_VERIFY_CB -DWOLFSSL_NO_ASN_STRICT"
)
