add_wolfssl(${bin_name}-wolfssl
	"4a30ffe2b817f7c6ca8005ea50bbc5d830557082" #Fix tap Werror
   "musl"
   "-DWOLFSSL_SMALL_STACK -DWOLFSSL_CUSTOM_OID -DHAVE_OID_ENCODING -DHAVE_OID_DECODING -DOPENSSL_EXTRA -DWOLFSSL_VERIFY_CB_ALL_CERTS -DWOLFSSL_ALWAYS_VERIFY_CB -DWOLFSSL_NO_ASN_STRICT"
)
